# Site settings
title: Fareed Javed 
email: fareedjaved@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 "Fareed Javed is an aspiring developer. He is currently a Senior at the University of Maryland." 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yuccabyte
github_username:  FareedJaved

# Build settings
markdown: kramdown
