# Site settings
title: Fareed Javed 
email: fareedjaved@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 "Hi! My name's Fareed Javed and I am an aspiring developer. Currently in my laster semester at University of Maryland. Here are some projects I've worked on.'" 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yuccabyte
github_username:  FareedJaved

# Build settings
markdown: kramdown
